version: '3'
services:
  product-service:
    build:
      context: ./packages/product-service
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
    depends_on:
      - cache
  cache:
    build:
      context: ./packages/cache
      dockerfile: Dockerfile
